// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfqphsfyghzucniybcga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcXBoc2Z5Z2h6dWNuaXliY2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTk2NTMsImV4cCI6MjA1ODg3NTY1M30.U-2MJnPS4dKueLFemtMaA_HV71FXBrBPo1_Q5irHPgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);